### ISSUE TITLE
Color issue when used together with dark theme

### ISSUE THREAD

**Issue by AndhikaWB** [lepennec/ggwordcloud#25]
Text doesn't show when this library is used together with `ggdark` theme
``` r
library(ggdark)

data("love_words_small")
ggplot(love_words_small, aes(label = word, size = speakers)) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 30) +
  dark_theme_minimal()
```

When not used with ggdark (ignore the overlapping text, too lazy to fix)
![image](https://github.com/user-attachments/assets/2738e4bc-ef63-4364-a2b6-c57c9e01e838)

---

When used with ggdark (see code above)
![image](https://github.com/user-attachments/assets/4347db02-c704-4476-b8be-5b4531277930)

---

Changing color to white via the `color` parameter also doesn't seem to produce white text, it will produce red/orange text instead
``` r
data("love_words_small")
ggplot(love_words_small, aes(label = word, size = speakers, color = 'white')) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 40) +
  dark_theme_minimal()
```
![image](https://github.com/user-attachments/assets/bc705b4c-2acd-4cdf-8c28-351b92156285)

**Comment by AndhikaWB** [comment]
Tested on both cairo (png) and svglite (svg) renderer

Here is my example Quarto markdown (`.qmd`) header:
```
---
title: Test
author: AndhikaWB
date: last-modified
date-format: long
format: gfm
knitr:
  opts_chunk:
    echo: true
    results: hold
    dev: svglite
    dev.args:
      scaling: 1.25
---
```
